# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Intro Stats
author: Alexander Clark, Columbia University
logo: images/statLogo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - bib.bib
bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/alexanderthclark/Stats1101  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  theme: sphinx_book_theme
  extra_css: ["_static/custom.css"]
  favicon: ./_static/norm_favicon.ico
  google_analytics_id: G-32DRGZQWDG


launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe                  : true

sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinx_togglebutton
    - sphinxcontrib.bibtex

thebe:
  repository_url: "https://github.com/alexanderthclark/Stats1101"
  branch: main
